### ISSUE TITLE
Deprecation SharedArrayByffer

### ISSUE THREAD

**Issue by mrangel-jr** [hcl1687/iframe-channel#19]
When i use the lib in my project, run locally using Chrome, show me "Deprecation in Shared ArrayBuffer. It works until May 2021". 
Another thing: Safari doesn't have SharedArrayBuffer, so i have problem to make a request the parent to child. 
But in example , when i try make a request connection by child , it works, by the request is pending, like a Promise not fulfilled.

The full message is : [Deprecation] SharedArrayBuffer will require cross-origin isolation as of M91, around May 2021

It shows in this command: typeof SharedArrayBuffer === 'function' ? new SharedArrayBuffer(profilingStateSize * Int32Array.BYTES_PER_ELEMENT) : // $FlowFixMe Flow doesn't know about ArrayBuffer
at webpack://hades/./node_modules/scheduler/cjs/scheduler.development.js

I believe that this package scheduler have been used by iframe-channel

I'm using in a mac Big Sur
Safari version: Versão 14.0.3 (16610.4.3.1.7)
Chrome version: 89.0.4389.90

**Comment by hcl1687** [comment]
@mrangel-jr 
Thank you! I will fix it before May 1st.

**Comment by hcl1687** [comment]
@mrangel-jr 
There are two issues:
1. Show "Deprecation in Shared ArrayBuffer. It works until May 2021" when running the demo project on chrome.
2. When trying to make a request connection by child , it works. but the request is pending, like a Promise not fulfilled.

About the first, it's not the iframe-channel's issue but the react's. As I am using create-react-app to build the demo project. It shows the message when running the project on chrome. To fix this issue, just update react to the latest version. Please refer to this link:
https://stackoverflow.com/questions/66489286/sharedarraybuffer-will-require-cross-origin-isolation-as-of-m91-around-may-2021

About the second, in the demo/parent/package.json, I use "set PORT=9876" to change the parent website's port. But It seems not working on Mac. After running the parent project on Mac, it's port is set to 3001, which will cause this issue. So I use cross-env to fix this issue.

I have pushed the commits:
a36e4cdba6d4a3ddc1723f1615c455014efb2a94
6651191874f81e5256fbeedc14ae2cfa27f33902

Please try again.

**Comment by hcl1687** [comment]
@mrangel-jr 
About the issue that you mentioned as follow:
But the first option (Parent request connect making connection on handleLoad) in the demo project doesn't run in Safari.
I'm using in a mac Big Sur
Safari version: Versão 14.0.3 (16610.4.3.1.7)

This is because that the iframe-channel instance in the child iframe hasn't be created before the parent's iframe-channel instance post the 'preconnect' message. 
To fix this issue, I enhance the iframe-channel to support reconnecting. When calling channel.connect(), if it's failed to connect the target, iframe-channel will try to reconnect after 1000ms, and will try to connect up to 10 times. You can set the maxAttemptInterval and maxAttempts to adjust these parameters when create the instance.

I have pushed the commits:
c8da187

Please try again.
